# Generated by Django 3.1.6 on 2021-02-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210205_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='body',
            new_name='lisst',
        ),
    ]
