# Generated by Django 3.1.6 on 2021-02-05 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210204_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='body',
            new_name='lisst',
        ),
        migrations.AlterField(
            model_name='list',
            name='todolist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist'),
        ),
    ]
