# Generated by Django 3.1.6 on 2021-02-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210205_1006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='lisst',
            new_name='lissts',
        ),
    ]
