# Generated by Django 3.1.6 on 2021-02-06 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210205_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('todolist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.todolist')),
            ],
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
